db:
  postgres:
    host: db
    port: 5432
    db: postgres
    user: postgres
    password: postgres

api:
  http:
    host: 0.0.0.0
    port: 6060

view_stat:
  redis:
    channel: viewstat
    addr: addr
    username: user
    password: password
    db: 0
  urls:
    - some_url
